# Generated by Django 5.1.7 on 2025-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_range", models.CharField(max_length=19)),
                ("end_range", models.CharField(max_length=19)),
                ("info", models.CharField(max_length=64)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start_range", "end_range"],
                        name="card_range_start_end_idx",
                    )
                ],
            },
        ),
    ]
