# Generated by Django 5.1.7 on 2025-03-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardrange", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cardrange",
            name="card_range_start_end_idx",
        ),
        migrations.AddIndex(
            model_name="cardrange",
            index=models.Index(
                fields=["-start_range", "end_range"], name="card_range_start_end_idx"
            ),
        ),
    ]
